@startuml packageDiagram
title Stereo Vision - Depth Estimation
'object level depth design

skinparam TitleFontStyle bold
skinparam linetype ortho
skinparam TitleFontSize 18
'skinparam TitleBackgroundColor #LightBlue
'left to right direction

skinparam packageStyle rectangle
skinparam packageFontSize 11
skinparam packageBackgroundColor #LightCyan

' Main components
package "Stereo Camera Capture" as Capture <<Hardware>> #LightGreen {
}


package Rectification {
      
}
package "Calibration Data" as Calibration <<Configuration>> {
    
}

rectangle "Stereo Processing Pipeline" as Pipeline <<Core>> #white {

    package "Object Detection (YOLO11n)" as Detection <<AI Model>>{
   
    }
    
    package "Detection Matching\n(sparse Correspondence)" as Matching {
        
    }

    package "Disparity Computation" as Disparity {
 
    }
    
    package "Depth Estimation\n(Triangulation)" as DepthCalc {
        
    }
    
    package "3D Reprojection" as Reprojection {
        
    }
    
}

package "Map Projection" as MapProj {
    
}

package "Map" as MainApp <<UI>> #FFC69D {
  
}

' Data flow connections
' run only once for efficiency
Capture --> Rectification: "L,R frames"
Rectification ---> Detection: "rectified frames\n L,R"
' sending 1 rectified image 'left' to yolo ??

Detection ---> Matching: " detection L,R\n(xL, yL)"
'using only detections on one camera 'left'??

Calibration ..> DepthCalc : <b>f,B</b>
Calibration ..> Rectification: " R1,R2,\n P1,P2"

Calibration ..> Reprojection : <b> f,cx,cy</b>

Matching --> Disparity : "matched(xR, yR)"
Disparity --> DepthCalc: "disparity"
DepthCalc --> Reprojection : "depth Z"
'(depth)
'DepthCalc -down-> Reprojection : Z 
Reprojection ---> MapProj : "(X,Y,Z)"
MapProj --> MainApp : "(map_x, map_y)"




Legend right
    Data flow: 
    <color:#FB2C36>Frames Capture → Rectification → Object Detection → Matching → Disparity → Depth → 3D → Map → UI</color>
    ----
    Formulas: 
       disparity: d = xL − xR
       Depth: Z = (f × B) / d
       Reprojection:
       X = (x - cx) × Z / f
       Y = (y - cy) × Z / f 
    ----
end Legend

@enduml