@startuml ClassDiagram
title Software Diagram

skinparam TitleFontStyle bold
skinparam TitleFontSize 20
skinparam TitleBackgroundColor #LightCyan


skinparam lineType ortho
skinparam classAttributeIconSize 0
skinparam classFontSize 11
skinparam packageStyle rectangle


package "PyQt6.QtWidgets" <<Framework>> {
    class QWidget {
    }
    
    class QMainWindow <<UI>>  {
    }
    
    class QApplication {
    }
}

package "PyQt6.QtCore" <<Framework>> {
    class QTimer {
        +timeout: Signal
        +start(int): void
    }
}

package "External Libraries" <<Framework>> {
    class Picamera2 {
        +__init__(index: int)
        +create_preview_configuration(main: dict): Config
        +configure(config: Config): void
        +start(): void
        +capture_array(): ndarray
    }
    
    class YOLO {
        +__init__(model_path: str)
        +__call__(frame: ndarray, stream: bool): Results
    }
}

class DebugWindow <<UI>> #FFC69D {
    - cameraDisplaySize: float
    - cameraResolution: tuple
    - camIds: tuple
    - camL: QLabel
    - camR: QLabel
    - camera1: StereoCamera
    - camera2: StereoCamera
    - timer: QTimer
    - fpsLabel: QLabel
    - frameTimeLabel: QLabel
    __
    + __init__()
    + start_capture(): void
    + update_metrics(time_start: float, time_end: float): void
    + cv2_to_qt(cv_img: ndarray): QPixmap
}

class MainApp <<UI>> #FFC69D  {
    + __init__()
}

class StereoCamera  {
    - index: int
    - camera: Picamera2
    - model: YOLO
    - config: Config
    __
    + __init__(index: int, resolution: tuple)
    + get_frame(): ndarray
}

' Inheritance relationships
QWidget <|-- DebugWindow
QMainWindow <|-- MainApp


' Composition relationships
DebugWindow *-- "1" QTimer : timer
DebugWindow *--- "2" StereoCamera : camera1, camera2
StereoCamera *-- "1" Picamera2 : camera
StereoCamera *-- "1" YOLO : model

' Dependencies
DebugWindow .up.> QApplication : runs in
DebugWindow .down.> cv2 : uses
DebugWindow .down.> time : uses
StereoCamera ..> cv2 : uses
StereoCamera ..> numpy : uses



note left of MainApp #ffff18ff
  (nog niet gemplementeerd).
  zal de Map met de punten weergeven
end note


legend top right
  | Color | Meaning |
  | <#FFC69D> | UI classes |
  | <#ffff18ff> | Notes |
end legend


@enduml